### ISSUE TITLE
Need a big example

### ISSUE THREAD

**Issue by croupier** [COCOPi/cockpit#136]
Hi. Сan you show any complete project on the cockpit? Same like best practice.
I want to look: 
 how to organize customizable menu with hierarchy?
 how to use global (for my app and cockpit admin panel) auth / ACL for separate anonimus, admin and other users? I want to add same controls on pages for admin.
 where is right way to use cache, session?
 that is block in $app object (can't find setter)? 
 how manage regions visibility by dynamic conditions?
 how to add js callback on form success / error event?
 how enable debug and view and trace errors? 
 how add a handler to collection item CRUD events?
 and many other noob questions )

Now i try to find out all in cockpit / lime / mobgolite docs, but complete working example is match better for me.

Offtopic:
1. Have you plans to add multiple option for all fields type like in collection link?
2. Using sqlite and sort on big collection (500+ almost empty items) is seriously slows down query. Mongodb had no problems this? How about queries with many conditions on many fields collection? Sorry, can't test it by myself now.

I want to understand how to build user friendly app not only for me, but for client too.

Thanks, and sorry for my english again.

**Comment by davidprati** [comment]
+1
