### ISSUE TITLE
Lexy Documentation

### ISSUE THREAD

**Issue by nblackburn** [COCOPi/cockpit#141]
It would be nice to have some documentation on how Lexy works as i would like to use it in the views for the project i am working on.

- Content blocks `@block('example')`
- Assets

At the moment i am trying to make sense of the code that already does this but it's not all that clear.

**Comment by jbrooksuk** [comment]
What does Lexy offer than Blade doesn't?

**Comment by nblackburn** [comment]
@jbrooksuk It seems to be more stripped back.

**Comment by jbrooksuk** [comment]
Thanks :)

**Comment by amdad** [comment]
+1 for some docs.
