### ISSUE TITLE
Custom Folder for Storage

### ISSUE THREAD

**Issue by thinkink** [COCOPi/cockpit#219]
I tried to change the storage directory, in <b>custom/bootstrap.php</b>. After i change de database in <b>custom/config.php</b>

<pre>
'database'	=> [ "server" => "mongolite://".(COCKPIT_DIR. "/" . COCKPIT_FOLDER_STORAGE . "/data"), "options" => ["db" => "cockpitdb"] ],
</pre>
 but there is a problem in the configuration, not that way you could set from the config.php file.

I have a error in paths images in galleries module.

I think the problem is in cache path in  <b>/root/bootstrap.php</b>. It gets the original path before i change in custom configuration.
<pre>
 // set cache path
        $tmppath = $app->path('cache:tmp');
<pre>

**Comment by piotr-cz** [comment]
Changing database storage path as described in the [documentation](http://getcockpit.com/docs#!getting_started/security) does not apply.

Cockpit creates an empty `cockpit.memory.sqlite` file in new location, but still uses the path that is described in the config.database.server variable (default is `'mongolite://' . (COCKPIT_DIR . '/storage/data')`).

So to change location of SQLite database file, both should be changed:

```php
return [
    'database' => [
        'server' => 'mongolite://[your-custom-path]'
    ],
    'paths' => [
        'data' => '[your-custom-path]'
    ],
];
```
