### ISSUE TITLE
Media manager not sorting files properly

### ISSUE THREAD

**Issue by zakbach** [COCOPi/cockpit#244]
As far as I can tell, it's not sorting files neither by filename or date added, creating a really confusing way to attach files to a collection item if there's a lot of files. Example:

![201216](https://cloud.githubusercontent.com/assets/10362886/5592897/a68c90fe-91f2-11e4-9a4c-0d7a33d1d907.png)

If this is intentional, then could anyone tell me according to what does it sort?

**Comment by AC10** [comment]
It usual work with 0 in front of the number, but in this case it doesn't

**Comment by zakbach** [comment]
@AC10 I tried with 0001, 0002 and so forth, still same.

**Comment by aheinze** [comment]
sorry, but I can't confirm this issue...which os do you use?

**Comment by zakbach** [comment]
Ubuntu 14.04 64bit on Digital Ocean.

**Comment by marktheis** [comment]
I have the same problem on Ubuntu 14.04 on Digital Ocean. But not on my local machine.
running cockpit 0.13.0.

This is my PHP info from the cockpit dashboard on Ubuntu:

```
Version	5.5.24
PHP SAPI	fpm-fcgi
Loaded Extensions	Core, date, ereg, libxml, openssl, pcre, sqlite3, zlib, calendar, ctype, dom, fileinfo, filter, ftp, hash, iconv, json, SPL, PDO, bz2, posix, Reflection, session, SimpleXML, snmp, soap, sockets, standard, tokenizer, xml, xmlreader, xmlwriter, zip, mysqlnd, cgi-fcgi, bcmath, Phar, curl, mbstring, gd, gettext, imap, intl, exif, mcrypt, mysql, mysqli, odbc, pcntl, pdo_mysql, PDO_ODBC, pdo_sqlite, readline, shmop, tidy, xsl, Zend OPcache

Memory limit	256M
Upload file size limit	512M
```
And this is on my local machine:

```
Version	5.5.18
PHP SAPI	apache2handler
Loaded Extensions	Core, date, ereg, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, SPL, iconv, intl, json, ldap, mbstring, mysql, mysqli, session, PDO, pdo_sqlite, standard, posix, Reflection, Phar, SimpleXML, soap, sockets, exif, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zip, apache2handler, imap, gettext, mcrypt, yaz, pgsql, pdo_pgsql, pdo_mysql
Memory limit	128M
Upload file size limit	32M
```
I have tried switching to php 5.4 and 5.6 but that doesn't make a difference.

**Comment by Hefesto** [comment]
Sorry about commenting an old ticket, i always had this issue and i'm still having it with the cockpit-next finder.
I'm not a developer but i believe this is related to `RecursiveIteratorIterator` in the [`protected function getfilelist()`](https://github.com/COCOPi/cockpit/blob/next/modules/Cockpit/Controller/Media.php#L268). I did a Google search and found [this comment](http://php.net/manual/en/class.recursivedirectoryiterator.php#120971). Not sure if this gives any hint on fixing this. The issue suggests that the `RecursiveDirectoryIterator` does not sort the files alphabetically on Linux.

Thank you.
```
PHP: 5.5.9-1ubuntu4.17
PHP SAPI: cli-server
System: Linux ubuntu 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64
Loaded Extensions: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, pcntl, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, cli_server, PDO, curl, gd, imagick, intl, json, mcrypt, mongo, mysql, mysqli, pdo_mysql, pdo_sqlite, readline, sqlite3, mhash, Zend OPcache
```
![finder](https://user-images.githubusercontent.com/705553/27478441-8dbef61a-5807-11e7-87c5-6f096c0dc464.jpg)

**Comment by Hefesto** [comment]
Just found there's a pull request fixing this issue #381. Would be nice to see it merged.

**Comment by aheinze** [comment]
Hi,

with the next commit, there will be an option for files ordering in the finder (sort by name, size, modified) ... so all files are sorted on the client side. this should fix this issue.
