### ISSUE TITLE
read only api key

### ISSUE THREAD

**Issue by estudiooka** [COCOPi/cockpit#246]
some advice on creating a read only api key would be great. thanks

**Comment by aheinze** [comment]
I'll make a tutorial how to use rules for api keys soon

**Comment by okadesign** [comment]
Thanks

**Comment by andrewkdesigns** [comment]
ETA on this?

**Comment by iamso** [comment]
+1

**Comment by iamso** [comment]
@aheinze any news on that?

**Comment by aheinze** [comment]
right any api access should be read only

**Comment by iamso** [comment]
@aheinze that would be nice as a default, but can you still provide a tutorial (or update the docs) about the permission rules for api keys?

**Comment by iamso** [comment]
@aheinze I'm interested in the access rules, because I would like to be able to give different api keys access to different content *(i.e. by group)*
