### ISSUE TITLE
Feature : import JSON

### ISSUE THREAD

**Issue by Chloee** [COCOPi/cockpit#256]
JSON Export feature is so nice, I would like to edit my export json file and import it after to gain more time when I have to do lots of modifications

**Comment by piotr-cz** [comment]
See this blogpost: [Import data into Cockpit collections
](http://getcockpit.com/blog/import-data-into-cockpit-collections)

If your database structure is different, you should map data to current fields - you may try my module: [cockpit-import](https://github.com/piotr-cz/cockpit-import).
