### ISSUE TITLE
Install cockpit as a composer dependency

### ISSUE THREAD

**Issue by youknowriad** [COCOPi/cockpit#261]
Hi, Is there a way yo install cockpit as a composer dependency and have the custom config outside the vendor folder.

Thanks a lot

**Comment by aheinze** [comment]
hi,

the only possible way I can think of are composer scripts: https://getcomposer.org/doc/articles/scripts.md

**Comment by youknowriad** [comment]
Hi,

I think if cockpit is intended to be for developers, it should be easy to install and update with developers tools (composer pour PHP). I think your point (am I wrong) is to make easy to use, juste copy/paste and launch a webserver, but for many developpers like, we want to be able to add the cockpit code to .gitignore and we want it to be outside the public path, update it easily with composer and custom some paths (cache, storage).

I've tried some things, override some consts and symlink assets, but I've not the required knowledge of how the CSM is organised to make this work. May be you should consider having two install methods ? one with composer with the ability to custom paths and one copy/paste method.

Thanks

**Comment by omnilight** [comment]
I agree with @youknowriad , you should provide way to customize paths for cockpit out of the box.

For example currently I see one problem: you define `bootstrap.php` in your composer.json and this makes it impossible to change any constants in this file after composer load.

Maybe you should exclude this file from autoloading, or at least maybe create separate repository that can be used for composer dependecies, and another repository for installing cockpit as standalone application

**Comment by piotr-cz** [comment]
I've got idea.
Maybe it would be possible trough [Composer Installers](https://github.com/composer/installers).

_If there would a package type **public** with destination of public subfolder (`public` or `web`)_,
and Cockpit's composer.json would look like:
```
"name": "aheinze/cockpit",
"type": "public",
"extra": {
    "installer-name": "cockpit"
}
```
then using composer it would be installed to `public/cockpit` folder.

**Comment by youknowriad** [comment]
@piotr-cz Not a bad idea

**Comment by piotr-cz** [comment]
Maybe cleaner way is to register _cockpit_ installer type for composer.
Additionally it would open possibility to install modules using composer:

**Cockpit application**
destination: `public/cockpit`
```json
{
  "name": "aheinze/cockpit",
  "type": "cockpit-core",
  "extra": {
    "installer-name": "cockpit"
  }
}
```

**Example module**
destination: `public/cockpit/modules/addons`
```json
{
  "name": "vernodorName/FooBar",
  "type": "cockpit-module",
  "extra": {
    "installer-name": "FooBar"
  }
}
```

Downside is that the public folder should be pre-set (hardcoded) in the installer type.

**Comment by aheinze** [comment]
@piotr-cz awesome

**Comment by piotr-cz** [comment]
I vote for `public` name as it seems most explicit to me. By inspecting Base [installer.php](https://github.com/composer/installers/blob/master/src/Composer/Installers/Installer.php) file
maybe it's possible to change it in root composer.json file with handling something like `extra.publicPath`.

**Comment by aheinze** [comment]
do I need to change anything in cockpits composer.json?

**Comment by piotr-cz** [comment]
- you should submitting pull request to [composer installers repo](https://github.com/composer/installers)
- change the type in cockpit's `composer.json` schema

I'm not sure I understood correctly the purpose of `installer-name` but IMHO it doesn't make sense to play with it without above steps anyway.

BTW: All of this is theory, I haven't tried it out.

**Comment by piotr-cz** [comment]
Another option would be to create an installer similar to Laravel installer ([GitHub repo](https://github.com/laravel/installer), [Docs](http://laravel.com/docs/5.0/installation)) or Lumen installer ([GitHub repo](https://github.com/laravel/lumen-installer), [Docs](http://lumen.laravel.com/docs/installation)).

**Comment by jbrooksuk** [comment]
This would be idea for us, since we build our websites with Laravel, we just want to use the helper methods `collection` or `region` etc within our existing code. We handle routing etc, but want to use the helpers only.

**Comment by piotr-cz** [comment]
One more and maybe most easiest option is to treat Cockpit like a frontend component (jQuery/ Bootstrap) using [Component Installer for Composer](https://github.com/RobLoach/component-installer)

So in projects `composer.json` file we'd define
```json
{
    "require": {
        "components/cockpit": "~0.13"
    }
}
```

**Comment by royduin** [comment]
Any updates on this one?

**Comment by royduin** [comment]
Relevant to this issue: https://github.com/mnsami/composer-custom-directory-installer/issues/11

**Comment by piotr-cz** [comment]
I've added support for Cockpit modules as composer installers.
New version that includes aforementioned commit It's not released yet

See https://github.com/composer/installers/pull/284 for details.

**Comment by omzy83** [comment]
So, what is the process for installing Cockpit as a Composer dependency? For example I want to use Cockpit as a CMS for Laravel, since it is a 3rd party package it should be installed to the vendor folder, and not manually copied to the public folder. The Cockpit storage folder can/should exist in the public folder however.

What is the correct way of doing this?
