### ISSUE TITLE
Same data in development and production

### ISSUE THREAD

**Issue by oaltman** [COCOPi/cockpit#285]
Is there any best practise how to easily sync cockpit data between production server and local machine ? I use git a and git-ftp for version control and deployment, but I cannot figure out how to easily synchronize cockpit data. Is there any working solution? Thanks

**Comment by aheinze** [comment]
hi, 
there are no sync / migration tools. or do you also want to add the cockpit data to git?

**Comment by oaltman** [comment]
I have only FTP access to production hosting. So I am not able to commit changes from there. Im sure I am not only one who have this kind of problem. On my local machine I am missing entries added on production server.

**Comment by prisme** [comment]
hi, I would also like to know how to transfer data from an instance to another ?

also, I noticed that after commiting .sqlite files to version control, I couldn't login anymore and had to reinstall cockpit. Nothing too terrible but maybe it could be mentioned in the installation wiki ?

**Comment by piotr-cz** [comment]
I'm using custom gulp task which ftp's all files that are newer then last task timestamp.
With excludes I omit the .sqlite files to not overwrite user changes.
