### ISSUE TITLE
User group root path erased when group is renamed

### ISSUE THREAD

**Issue by vdaguenet** [COCOPi/cockpit#289]
Hi!

I created a user group with some access controls and a root path. I saved. All was good. I decided to rename my user group and then my root path settings wasn't here anymore.

**Comment by NinaArens** [comment]
I experience the same bug except that it is erased every time you navigate away from the user group section and then return. The value does not actually get written to the database. It works when manually adding the path to cockpit.acl.groups.settings -> user -> media.path.
