### ISSUE TITLE
Collection link in region

### ISSUE THREAD

**Issue by jwhscholten** [COCOPi/cockpit#321]
I've created a region with a 'Collection link', linking to an existing collection. However, my regions output is empty. I'm also not sure what output to expect, basic idea is to create a menu by populating the region with collection links. Is this even possible?

**Comment by peterbrinck** [comment]
I can't figure it out either.. 
I've just in the template-tab, added my loop. But I find that very hard to work with.
I would love to know how to use the collection link!!
