### ISSUE TITLE
Wtf with links in wysiwyg mode?

### ISSUE THREAD

**Issue by riartem** [COCOPi/cockpit#340]
Hi, developers!
If I edit content in wysiwyg mode and insert link all ok. 
Example: /ru/docs/view/another-document
But after saving links look like: ../../../../docs/view/another-document

How to fix that? I would like to keep links stay such I make them

**Comment by charkes** [comment]
I believe that's TinyMCE's relative URL setting.  It should be fixed with https://github.com/aheinze/cockpit/pull/334
