### ISSUE TITLE
Remove PHP Dependency from Forms

### ISSUE THREAD

**Issue by Naatan** [COCOPi/cockpit#342]
I love the concept of cockpit; to have a CMS that is disconnected from the actual site. The CMS just does its thing and then the CMS can use the content generated by the CMS via the API.

Unfortunately the forms dont work this way, you need to literally pull in the CMS in order to display a form. Why can't we use the API for this as well? Just provide an endpoint where we can submit the data, or even better - just provide an API where we can submit it, let us worry about how we gather the data.

I understand it is technically possible, but it would be nice if cockpit facilitated it through its UX. I have to say I felt embarrassed for cockpit that it was suggesting I use PHP and use cockpit as a dependency. Both of those are a no-go and kind of the reason I am looking at a CMS like cockpit in the first place.

**Comment by piotr-cz** [comment]
There is an API for forms (trough not documented), look into to Forms module [bootstrap](https://github.com/aheinze/cockpit/blob/0.13.0/modules/core/Forms/bootstrap.php#L5), and widget generated [by default](https://github.com/aheinze/cockpit/blob/0.13.0/modules/core/Forms/views/api/form.php).

It should be possible to create custom module for generating custom form (you need that to insert form name and csrf token), set the action to aforementioned API endpoint.
If you don't want to use PHP, you'd probably need to retrieve these using custom API which would be a cockpit module.
