### ISSUE TITLE
Get the prev/next posts in JS

### ISSUE THREAD

**Issue by manudurgoni** [COCOPi/cockpit#343]
Hey,

I really appreciate Cockpit !

But I've a problem to get the prev/next posts from a current entry.

I'd like to have the posts just before and after my entry with _id `_this.actualite._id`

I've found in the mongoDB docs the `$lt`and `$gt` but how I can use those properties ?

I've tried this, but it doesn't work :

``` js
Cockpit.request('/cockpit/call', {
    module: 'collections',
    method: 'find',
    args: [
       'Actualites', {
          filter: {
             'categorie': _this.categorie._id,
              _id: {
                 $lt: _this.actualite._id
              }
           },
           limit: 1,
           sort: {
             _id: -1
           }
        }]
        }).success(function(item) {
          console.log(item);
          console.log(item[0].titre);
      });
```

Maybe someone can help me :)

Thanks

**Comment by piotr-cz** [comment]
Why won't you load whole collection (respecting the order), lookup current entry and pick previous/ next entries from an array?
That's how it's done for example in [Joomla CMS](https://github.com/joomla/joomla-cms/blob/3.4.3/plugins/content/pagenavigation/pagenavigation.php#L172). You could also add a _collection-link_ type field and set up these manually.

The `$lt` and `$gt` are comparators when picking up entries based on criteria, I think it's better to use them in conjunction with an custom-order field.
BTW: I have bad experience with filtering the `_id` field, Cockpit handles this propety in a different way.

**Comment by manudurgoni** [comment]
Yep, I thought to your solution, but as you wrote, finally I needed to find previous / next entries based on a custom field (a date selected by editor).


```js
// Previous entry
Cockpit.request('/collections/get/Entries', {
  filter: {
    'date': {
      '$lt': _this.entry.date
    },
    'category': _this.category._id
  },
  limit: 1,
  sort: {
    'date': -1
  }
})

// Next entry
Cockpit.request('/collections/get/Entries', {
  filter: {
    'date': {
      '$gt': _this.entry.date
    },
    'category': _this.category._id
  },
  limit: 1,
  sort: {
    'date': 0
  }
})

```

At first it did not work, but I noticed that the $lt / $gt filters in MongoLite did not allow to compare a string (and my entry's date was a string).

So I fixed this in MongoLite to solve my problem:


```php
// cockpit/vendors/MongoLite/Database.php
private static function evaluate($func, $a, $b) {
  $r = false;

  switch ($func) {

    ...

    case '$gte':
      if (is_numeric($a) && is_numeric($b)) {
        $r = $a >= $b;
      } else if (is_string($a) && is_string($b)) {
      $r = $a >= $b;
    }
    break;

    case '$gt':
      if (is_numeric($a) && is_numeric($b)) {
        $r = $a > $b;
      } else if (is_string($a) && is_string($b)) {
        $r = $a > $b;
      }
      break;

    case '$lte':

      if (is_numeric($a) && is_numeric($b)) {
        $r = $a <= $b;
      } else if (is_string($a) && is_string($b)) {
        $r = $a <= $b;
      }
      break;

    case '$lt':

      if (is_numeric($a) && is_numeric($b)) {
        $r = $a < $b;
      } else if (is_string($a) && is_string($b)) {
        $r = $a < $b;
      }
      break;

    ...
  }
}

```

PS : I don't speak english very well so if you don't understand, tell me ! ahah :)

**Comment by piotr-cz** [comment]
what is the example output for date field?

**Comment by manudurgoni** [comment]
The output is like this : `2015-06-17`. But yes, I would have had the same result by parsing the array with all entries.

**Comment by piotr-cz** [comment]
My point is that probably the `is_numeric` check is not required in [variables checking](https://github.com/aheinze/cockpit/blob/0.13.0/vendor/MongoLite/Database.php#L262). PHP is capable of comparing strings and even if this wouldn't usually make much sense, it does when comparing dates in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format, in case like yours.

**Comment by manudurgoni** [comment]
Yep you've right, I just added the condition with `is_string($a) && is_string($b)` to not change too much the original code of MongoLite. Thank you for your feedback.

**Comment by piotr-cz** [comment]
Well, this is because I'd say it's good candidate for pull request. I think the checks may be removed altogether.

By the way: I just recall that every entry has `created` and `modified` values, which are unix timestamps. You could use these instead of having editor to set it manually.

**Comment by manudurgoni** [comment]
Yes good idea !

Publishers want to be able to edit the publication date of an entry. That's why I have a date custom field.
