### ISSUE TITLE
Not working in subdirectory

### ISSUE THREAD

**Issue by Norcoen** [COCOPi/cockpit#344]
My site is running as `example.com/xx/yy/index.php`, so cockpit would be running as `example.com/xx/yy/cockpit/`

But `example.com/xx/yy/cockpit/` shows:

```
Warning: strpos(): Empty needle in C:\web\pao\cockpit\bootstrap.php on line 21
404

Uuuups, Page not found.
```

and `example.com/xx/yy/cockpit/install` redirects me to `example.com` (showing 404 Object not found in my case, because there is no root, only alias for /xx/yy/)

Kind regards,
Frank

**Comment by florianletsch** [comment]
Could you please specify what is "not working"? Thanks.

**Comment by Norcoen** [comment]
Sry, I hit the Comment button by mistake, I wasn't done writing

**Comment by Norcoen** [comment]
no ideas why cockpit cannot run from a subdirectory?

**Comment by aheinze** [comment]
which webserver do you use? which OS?

**Comment by qiualiang** [comment]
I also have this problem. By the way, my OS is Mac, and the server is apache 2.4.16

**Comment by visit1985** [comment]
Just hit this bug in Apache/2.4.6 on CentOS 7.

Concider the following (reduced) httpd.conf
```
DocumentRoot "/var/www/html"

Alias /cockpit /opt/cockpit/html

<Directory /opt/cockpit/html>
        Options +FollowSymLinks
        AllowOverride all
        Require all granted
</Directory>
```

The problem seams to be the calculation of `$COCKPIT_BASE` in `bootstrap.php`.
The `str_replace()` does not work, when `$COCKPIT_DOCS_ROOT` is not part of `$COCKPIT_DIR`.

Can't you work with `$_SERVER['QUERY_STRING']` instead of `$_SERVER['DOCUMENT_ROOT']` to calculate `$COCKPIT_BASE`?

**Comment by ivomarino** [comment]
it seems also that we have issues with symlinks, e.g.:

```
root@node:/var/www/vhosts/site# tree -a
.
├── current
│   └── public
│       └── branch
│           ├── master -> /var/www/vhosts/site/releases/master
│           └── test-branch-01 -> /var/www/vhosts/site/releases/test-branch-01
└── releases
    └── test-branch-01
    └── master
```

`DOCROOT` is `/var/www/vhosts/site/current/public`, in that case http://site.net/branch/master fails as far as we're using symlinks. If `/var/www/vhosts/site/current/public/master` is a directory all seems to be fine.
