### ISSUE TITLE
Feature: One column per collection field in the database.

### ISSUE THREAD

**Issue by marktheis** [COCOPi/cockpit#353]
Are there any plans to have each collection field as a column in the database?

Right now it is all stored as a JSON blob in the document column in collections.sqlite . It would be a lot easier to work with the database outside of Cockpit if it were stored in a relational database structure.

**Comment by peterbrinck** [comment]
I don't know if @aheinze has changed the way Cockpit stores data in the sqlite files, in [Cockpit Next](https://github.com/aheinze/cockpit/tree/next), but you could take a look

https://github.com/aheinze/cockpit/tree/next

**Comment by marktheis** [comment]
I've just checked Cockpit Next and it's stored in the same fashion as Cockpit. But maybe that will change. It looks very nice.

**Comment by malles** [comment]
I can see your point, but for the Keep It Simple flexible way Cockpit is built, this is the most sensible solution.
The database collection helpers help handle, search and sort the data, but outside cockpit that is harder, I agree.
If you want to use your database outside Cockpit, and do want to use the nicyness of Cockpit, I advise you to write a custom module, and create your db-scheme there.

**Comment by marktheis** [comment]
I would love to write a module for the community but I'm not that experienced in php. I think Cockpit has really good interface, which is why I'm here.

If that's the case then I don't understand why cockpit use sqlite at all then. Cockpit could store the JSON in plain JSON files. It wouldn't impact the performance as it is not utilising the features and speed of sqlite anyway. And that would make it more compatible with shared hosting providers that doesn't support sqlite.

I would also think that you would run into performance issues with a large db. sql is a lot faster than searching through JSON. But I guess you would recommend upgrading to mongoDB if that were the case?
