### ISSUE TITLE
Undefined index: title (lexy.php) and json_encode(): Invalid UTF-8 sequence (admin.php)

### ISSUE THREAD

**Issue by schutterskwartier** [COCOPi/cockpit#358]
I recently noticed a large error.log file filled with thousands of the here under line on a Cockpit powered one-page website:
`PHP Notice:  Undefined index: title in /public_html/cockpit/vendor/Lexy.php(429) : eval()'d code on line 9`

and in the cockpit directory there's another error.log file with:
`PHP Warning:  json_encode(): Invalid UTF-8 sequence in argument in /public_html/cockpit/modules/core/Cockpit/admin.php on line 94`

Yesterday I created another one-page and the same errors shows up.

Thought I'd report it.

Best regards,
Dennis

**Comment by aheinze** [comment]
do you try to output ```$title``` somewhere (region?)...seems there is no field/variable name **titlte**

**Comment by schutterskwartier** [comment]
Thank you for your quick reply!

You are right, `title` wasn't in the collection anymore.

As for the error on the other page:
`PHP Notice:  Undefined index: Datum in cockpit/vendor/Lexy.php(429) : eval()'d code on line 16`
`PHP Notice:  Undefined index: Extra in cockpit/vendor/Lexy.php(429) : eval()'d code on line 16`

`Collection Verjaardagen` (birthdays)  contains three text fields `Naam` (name), `Datum` (date) and `Extra`.

In a `Region` I use:
 `<?php foreach(collection("Verjaardagen")->find() as $item): ?>`
`      <li>`
`        <?php echo $item["Datum"];?>`
`        <?php echo $item["Naam"];?>`
`        <?php echo $item["Extra"];?>`
`      </li>`
`   <?php endforeach;?>`

I can't quite figure out what goes wrong.

My apologies for being a (partial) noob.

Best regards,
Dennis

**Comment by aheinze** [comment]
try ```<?php echo @$item["Datum"];?>``` / ```<?php echo @$item["Extra"];?>```
