### ISSUE TITLE
ID field for entries in collection (with auto-increment)

### ISSUE THREAD

**Issue by baptistebriel** [COCOPi/cockpit#366]
Is there a way to add an "ID" field in a collection that will be incremented automatically? So each post has its own ID (from 1 to whatever...) based on creation date. Maybe this should be here by default.

Thanks for building cockpit!
Looks really nice, and easy to use.

**Comment by aheinze** [comment]
you have always the unique  ```_id``` field.

**Comment by baptistebriel** [comment]
Yes, I did notice that — but I would need an `id` starting from 1 that will be incremented..

Because an `id` like `56178b60e2696doc2029773992` isn't really useful on the front-end part.

Imagine this simple use case:

`views/index.php`

```php
<?php $index = 1; ?>
<?php $length = count($posts); ?>
<?php foreach ($posts as $post): ?>
	<div class="item"
		data-item="<?php echo $index; ?>"
		data-slug="<?php echo $post['title_slug']; ?>"
		data-href="/blog/<?php echo $post['title_slug']; ?>">
	</div>
	<?php $index++; ?>
<?php endforeach; ?>
```

`views/article.php`

```php
<div class="item"
	data-item="<?php echo $post['index']; ?>"
	data-slug="<?php echo $post['title_slug']; ?>"
	data-href="/blog/<?php echo $post['title_slug']; ?>">
</div>
```

`$post['index']` would be the same as `$index` in the loop.

Let me know if you have any ideas. Thanks!

**Comment by baptistebriel** [comment]
I came up with a workaround by basically checking the array of posts, and then return the key index of the current's post...

```php
$app->bind("/work/:id", function($params) use($app) {
	
	$posts = collection('blog')->find()->toArray();
	$post = collection('blog')->findOne(["title_slug"=>$params['id']]);
	
	if(is_null($post)) {
		return $app->render('views/404.php');
	} else {

		$id = array_search($post, $posts);
		$id = $id++;

		$data = array(
		  "post"  => $post,
		  "id"    => $id,
		  "count" => count($posts)
		);

		return $app->render('views/article.php', $data);
	}

});
```

It works.. But I think this should be included by default. ;)
