### ISSUE TITLE
How to get all locales/languages?

### ISSUE THREAD

**Issue by royduin** [COCOPi/cockpit#368]
I'd like to create a language selector, but how do I get all the available languages? And how to create a multi language frontend with Lime? For example `/page` points to a page in the default language and `/en/page` to the English version?

**Comment by attitude** [comment]
Hi @royduin, try:

```php
// Use Lime\App public __get() method to retrieve nosql MongoHybrid\Client storage service.
// See: cockpit/vendor/MongoHybrid/Client.php for API reference
$db = cockpit()->db;
$locales = $db->getKey("cockpit/settings", "cockpit.locales", []);

print_r($locales);
```

Hope it works for you too.

**Comment by royduin** [comment]
Thank you! I'll try it
