### ISSUE TITLE
Site search functionality?

### ISSUE THREAD

**Issue by royduin** [COCOPi/cockpit#369]
Can't find anything about this, is it possible to search through the website on the frontend? Or do I've to build this with filters on multiple collections and use pagination for this?

**Comment by amdad** [comment]
Any info about that?

**Comment by peterbrinck** [comment]
There's not a build-in feature for search, you'll have to do it either by accessing the search function from the backend. on the frontend. Which is possible, everything in Cockpit backend is accessible on frontend. But if you don't want to mess with that, then you'll have to make it with filters when you get the content
