### ISSUE TITLE
Website routing not working on live server

### ISSUE THREAD

**Issue by arlg** [COCOPi/cockpit#371]
Hello,

I migrated my website to the live server today. But I get "Path not found." message when I want to load it. It's the same files and the server configuration supports Cockpit. 

What could be wrong in the live server ?

Do I have to change something in the .htaccess ? Is there other configuration variables to change ?

My .htaccess : 

```
<ifModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    #RewriteRule !\.(js|ico|gif|jpg|png|css|geojson|json)$ index.php [L]
    RewriteRule ^(.*)$ index.php?/$1 [QSA,L]
</ifModule>
```

Tell me if you need some other informations, I don't know what to do at all :/
I have the feeling that the server always falls back to / event when I try to load other page routes.

Thanks

**Comment by baptistebriel** [comment]
+1

**Comment by baptistebriel** [comment]
If you're using the latest OVH servers, this solved my issue:
http://www.grafikart.fr/forum/topics/11495

**Comment by peterbrinck** [comment]
Are you using shared hosting or a VPS where you have SSH access?
If NOT using shared hosting, check if all the files have the correct permissions and the correct owner
If there's no problems there, then maybe it's because of FastCGI.
 - If you're using FastCGI

FastCGI doesn't work well with Lime, the micro framework behind Cockpit
Me and Artur fixed it with some hacks

```php
$app = new Lime\App([
    'base_url'     => BASE_URL,
    'base_route'   => BASE_ROUTE,
    'route'        => preg_replace('#'.preg_quote(BASE_URL, '#').'#', '', parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH), 1)
]);
```

**Comment by arlg** [comment]
Thanks @baptistebriel (yes, one year later), it was that OVH issue... I've had it on another website going in production.
