### ISSUE TITLE
MySQL Support?

### ISSUE THREAD

**Issue by jpruiz114** [COCOPi/cockpit#377]
Hi, I would like to know if there's any support for MySQL?

Thanks!

**Comment by piotr-cz** [comment]
There is no support for MySQL.
I'm working on a experimental driver but due to NoSQL nature of how cockpit handle data, I'm sceptical it will work out. Event if it will, I there is high possibility there will be performance issues compared to SQLite or MongoDb drivers.

**Comment by stenrdj** [comment]
Any updates for using mysql with cockpit please?

**Comment by rickerd** [comment]
Is there any update on the DB solution?
I'm wondering what is possible for a DB solution since i now don't use a DB i guess. @piotr-cz

**Comment by piotr-cz** [comment]
Last time I checked the show stopper was lack of adapter for [`PDO::sqliteCreateFunction`](http://php.net/manual/en/pdo.sqlitecreatefunction.php) for non - NoSQL drivers such as MySQL (see [this comment](https://github.com/agentejo/cockpit/issues/175#issuecomment-57523471)).

Now it's being used only in [lib/MongoLite/Database.php](https://github.com/agentejo/cockpit/blob/0.5.5/lib/MongoLite/Database.php)).

I guess it could be emulated by creating a query that uses [CREATE PROCEDURE or CREATE FUNCTION](https://dev.mysql.com/doc/refman/5.7/en/create-procedure.html).

This is where I've got with my research.

**Comment by piotr-cz** [comment]
I'm working on MySQL driver for cockpit.
So far it seems to work fine, but it uses JSON functions so MySQL v5.7.9+ is required and some collection filters such as `$func` and `$fuzzy` probably won't be available.

In development environment with small collections it's ~5x slower than SQLite driver 

repo: https://github.com/piotr-cz/cockpit/tree/feature/mysql-driver

**Comment by piotr-cz** [comment]
I've decided to transform feature into [SQL Driver addon](https://github.com/piotr-cz/cockpit-sql-driver) for Cockpit.

Performance was slower due to large dev database.
