### ISSUE TITLE
Tag 0.13.1

### ISSUE THREAD

**Issue by jorrit** [COCOPi/cockpit#382]
According to the CHANGELOG document there is a version with number 0.13.1. However, I can't find a tag to download it. Could this be created?

**Comment by aavf** [comment]
The 0.13.1 changelog says: # Fixed made Cockpit PHP7 compatible.
I was able to run with no problems, until now, on PHP7 with version 0.13.0 so probably there was going to be a version 0.13.1 but then realised it wasn't necessary.
