### ISSUE TITLE
Where can I set starting folder for media browser?

### ISSUE THREAD

**Issue by zontarian** [COCOPi/cockpit#412]
Hi,

in Cockpit I could set the starting folder of the media browser, as specified in [Cockpit doc for mediamanager](http://getcockpit.com/docs#!modules/mediamanager).

> You can change the root path for each user group in Settings > Accounts by clicking on  Manage account groups and permissions and then switching to the group settings tab.

Now in Cockpit next I'd liek to be able to set it. Is there a directive to put in `config.yaml`?

Thanks

**Comment by JesperWe** [comment]
If you check out https://github.com/COCOPi/cockpit/blob/next/modules/Cockpit/admin.php#L30 there appears to be a possibility to do this. I haven't tested it myself, tough.

**Comment by zontarian** [comment]
Following another issue in this site, I've found it:
Just edito your `config.yaml` or (`config.php` file) and put something like this

    # admin specific
    groups:
        author:
        $admin: true
	      $vars:
	           finder.path: "../../public/media"
          cockpit:
              backend: true
              finder: true 

At the moment I have difficulties setting it for group `admin` but this works for other users. It can also exit from the `storage` dir.
