### ISSUE TITLE
[Cockpit-Next] PHP error on entry view when using MongoDB

### ISSUE THREAD

**Issue by gryphonmyers** [COCOPi/cockpit#416]
![image](https://cloud.githubusercontent.com/assets/5785304/15486264/49261ee8-20f9-11e6-8fe8-614bf71e20fe.png)

The Mongo client doesn't seem to handle null in the second parameter. Not sure if you'd want to fix this on the Mongo client side or the implementation side. I tried to figure out where null is getting passed in, but couldn't. 

This seems to happen 100% of the time when attempting to view a previously created entry.

**Comment by aheinze** [comment]
I haven't tested Next with MongoDB yet as there is a new MongoDb driver. Hope to get this done soon.

**Comment by gryphonmyers** [comment]
Oh! Does that mean we will get access to aggregation on the REST API? :D

**Comment by aheinze** [comment]
should be fixed
