### ISSUE TITLE
never encrypt passwords, just hash

### ISSUE THREAD

**Issue by DanielRuf** [COCOPi/cockpit#417]
Your hash function is not creating a (secure) hash.

There are several issues:
- [sec-key is hardcoded](https://github.com/COCOPi/cockpit/blob/0068941972c899ab669b4ea4197ba65afee8d500/bootstrap.php#L71) and no mention of this setting in the documentation
- [md5 is used for generating a hash](https://github.com/COCOPi/cockpit/blob/a8b783fc449c1cbd996d8dc7b2e757a03b7d832b/lib/Lime/App.php#L1124) which is pretty weak and fast, you should generally use `password_hash`
- [the used encode function](https://github.com/COCOPi/cockpit/blob/a8b783fc449c1cbd996d8dc7b2e757a03b7d832b/lib/Lime/App.php#L1134) is just a simple RC4 implementation, never roll your own crypto, use the internal encryption and hashing functions shipped with PHP
- [the decode function](https://github.com/COCOPi/cockpit/blob/a8b783fc449c1cbd996d8dc7b2e757a03b7d832b/lib/Lime/App.php#L1171) is just the same, which is just a [XOR function](https://github.com/COCOPi/cockpit/blob/a8b783fc449c1cbd996d8dc7b2e757a03b7d832b/lib/Lime/App.php#L1160)

https://github.com/COCOPi/cockpit/blob/0068941972c899ab669b4ea4197ba65afee8d500/bootstrap.php#L103
https://github.com/COCOPi/cockpit/blob/014605db35c13a033a35addfe8277ec1a4008450/modules/core/Cockpit/Controller/Accounts.php#L61

I highly recommend switching to `password_hash`, `hash_equals` and so on.

RC4 is not a CSPRNG, just a PRNG using a simple PRGA with an XOR key.

See
http://ideone.com/gvC3qU
http://crypto.stackexchange.com/a/3644
http://security.stackexchange.com/a/106145
http://security.stackexchange.com/a/2210
https://adambard.com/blog/3-wrong-ways-to-store-a-password/
https://en.wikipedia.org/wiki/RC4#Security
http://www.cryptofails.com/post/75204435608/write-crypto-code-dont-publish-it

PS: better update your software stack and hide these information:

Server: Apache/2.4.12 (Ubuntu)
X-Powered-By: PHP/5.5.30-1+deb.sury.org~precise+1

Server: Apache/2.4.10
X-Powered-By: PHP/5.6.16

**Comment by aheinze** [comment]
I fully agree on this, I'll fix that.

**Comment by DanielRuf** [comment]
Much better =)

`$algo = PASSWORD_DEFAULT`

But keep in mind that the used algorithm can change over time so an additional `password_needs_rehash` check + `password_hash` and upating the saved password hash makes sense for example if any of the internally used parameters (cost or algorithm) changes eg when migrating from one server to another where the supported algorithms differ.

Personally I would prefer setting this flag to PASSWORD_BCRYPT but PASSWORD_DEFAULT should be ok.

**Comment by aheinze** [comment]
@DanielRuf I updated it to PASSWORD_BCRYPT. As the next branch is still labeled alpha, I can make these changes ;-) Updating existing installations should be pretty easy. Just delete the accounts collection and re-run the installer.

according to hiding default header information: I think, this should be a duty of the server admin, not the app. like setting ```expose_php = off``` in the php.ini etc.

thanks for the suggestions!

**Comment by DanielRuf** [comment]
> Updating existing installations should be pretty easy. Just delete the accounts collection and re-run the installer.

Ah ok, thanks for the clarification.

> according to hiding default header information: I think, this should be a duty of the server admin, not the app. like setting expose_php = off in the php.ini etc.

Well, these are information from your websites / server and there were critical security patches since then. Just a nice hint to hide these details there ;-)
