### ISSUE TITLE
Media field & file types

### ISSUE THREAD

**Issue by tameroski** [COCOPi/cockpit#418]
In stable version 0.13.0, when i set a media field to only accept a list of extensions (like "jpg|gif|png"), i'm not able to pick a file with the first extension in the list (a jpg file in that case).
Not very important as the Media file type is now split into File and Image types in the master branch. Just for reference ...

**Comment by tameroski** [comment]
The right syntax for file extensions restriction is : *.(gif|png|jpg)

**Comment by jongirard** [comment]
> when i set a media field to only accept a list of extensions (like "jpg|gif|png")

This is something I need to do but I haven't been able to locate anything in documentation. What json options did you use to be able to restrict the file field type? @tameroski
