### ISSUE TITLE
Page not found /install

### ISSUE THREAD

**Issue by esod** [COCOPi/cockpit#419]
Using the [Nginx setup](https://github.com/COCOPi/cockpit-docs/blob/master/tutorials/nginx.md) configuration for my server block, /install returns "The page you are looking for is not found." 

This issue has been discussed in https://github.com/COCOPi/cockpit/issues/19. When I use another configuration which is working on my system for several Drupal installations:

```
server {
    server_name cockpit.local;
    listen 80;
    root /var/www/cockpit.local;
    access_log /var/log/nginx/cockpit.local-access.log;
    error_log /var/log/nginx/cockpit.local-error.log;
    index index.php;

    location / {
        try_files  $uri $uri/ /index.php?$args;
    }

    location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
        access_log off;
        expires max;
    }
    location ~ /\.ht {
        deny  all;
    }
    location ~ \.php {
        try_files $uri = 404;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
```
I can get to the Installation completed screen. But when I click `Start using Cockpit` and am sent to http://cockpit.local/index.php/auth/login, I get 404 Not Found. 

My server configuration is pretty old, but meets [cockpit's requirements](http://getcockpit.com/docs#!getting_started/requirements).
nginx version: nginx/1.0.15
PHP 5.5.36 (cli) (built: May 25 2016 16:10:36) 
SQLite version 3.6.20
CentOS release 6.8 (Final)
node v0.8.4
npm 1.1.45

Any help here will be greatly appreciated. Thanks.

**Comment by esod** [comment]
Never mind. This became a non-issue once we moved to node v.4.4.5 and subsequently npm 2.15.5. Thanks for the CMS.

**Comment by aheinze** [comment]
ok...greta to hear 👍
