### ISSUE TITLE
Stuck at first step - Simple blog implementation

### ISSUE THREAD

**Issue by laurent-d** [COCOPi/cockpit#424]
Hello @aheinze,

My issue is very silly and concern the front-end, i followed the tutorial for the beginning (https://github.com/COCOPi/cockpit/wiki/Simple-blog-implementation-with-a-router) but i am allready stuck with a Type 4 error.. like that : { "type": 4, "message": "syntax error, unexpected '='", "file": "\/home\/lawzadpu\/savary\/views\/index.php", "line": 2 }

It seems the server don't like <?php= 
I am on php 7 apache and all seems to be well setted.
In other part i tested the cocopikickstart and it work on the same server.

Any idea ?

**Comment by aheinze** [comment]
Please try ``<?=`` instead of ``<?php=``

**Comment by laurent-d** [comment]
Thanks a lot ! it solve the error but it don't display.
 Anything wrong with this in the BO
 :

Collections
-blog
--title
--content

?

![cockpit](https://cloud.githubusercontent.com/assets/6553086/17355913/56570940-5954-11e6-990e-47bd7a2148a4.gif)

**Comment by laurent-d** [comment]
Sorry, i found it, to many filter
