### ISSUE TITLE
Upload button open dialog but doesn't upload nothing

### ISSUE THREAD

**Issue by francocorreasosa** [COCOPi/cockpit#426]
Hi, 

When I want to upload a file, I select the file to upload but Cockpit does nothing at all.

Please Help! (Cockpit Legacy I suppose because it is from this repo)

**Comment by JesperWe** [comment]
This repo has both the legacy (master branch) and Next (next branch) versions. So it depends on which branch you have checked out. Run `git status` to find out.

If nothing happens when you upload you should first check your browser console for errors, then the server log.
