### ISSUE TITLE
Thumbnail creation from external images

### ISSUE THREAD

**Issue by utamir** [COCOPi/cockpit#430]
Maybe it is just missing functionality, but when i am using 
<?php thumbnail("https://somehost_external_host/image.png", 50, 50);?>
the output is 
`<img src="data:image/gif;base64,R0lGODlhAQABAJEAAAAAAP///////wAAACH5BAEHAAIALAAAAAABAAEAAAICVAEAOw==" alt="https://somehost_external_host/image.png">`

Obviously https://somehost_external_host/image.png image is exists.
The same output for all images, regardless of the actual source

**Comment by piotr-cz** [comment]
This is just a placeholder when image file is not accessible. Are you sure that creating thumbnails from URLs is supported? by Cockpit? which version are you using?
