### ISSUE TITLE
[Next] Importer does not trigger generation of slugs

### ISSUE THREAD

**Issue by gryphonmyers** [COCOPi/cockpit#452]
1) Create a collection with a field that has "slug":true in its options
2) Import entries into this collection
3) Look at the collection on the REST API - notice that no "_slug" version of the field is generated.
4) Open up one of the imported entries and click save
5) Look at the REST API again - now it has the sluggified field. 

Also should we allow importing values straight into the sluggified version of a field? I notice that the slug is no longer manually editable, but in the legacy version it was. If it's not editable, then I guess it should always generate a new value, but it does mean users upgrading from the legacy version will lose any customized versions of their slugs, which could be potentially disastrous for SEO depending on implementation.

**Comment by aheinze** [comment]
should be fixed with your PR
