### ISSUE TITLE
[Next][REST API] $in method on _id field 500s

### ISSUE THREAD

**Issue by gryphonmyers** [COCOPi/cockpit#460]
1) Use the following query string on the REST API (any collection) 
`&filter[_id][$in][0]=xxxxxxxxxxxxxxxxxx`
2) Note that it 500s
3) Use the following query string on the REST API (any collection) 
`&filter[name][$in][0]=MyEntryName`
4) Note that it does not 500

Forgot to mention - this is using MongoDB.

This does not appear to work either, though instead of a 500 it gives me "path not found":
`&filter[$or][0][_id]=xxxxxxxxxxxxxxxxxx`
Again, the equivalent with a different field seems to work just fine:
`&filter[$or][0][name]=MyEntryName`

**Comment by aheinze** [comment]
I see, and think to know wat's the cause of the problem. should be fixed soon.

thanks for the hint!

**Comment by gryphonmyers** [comment]
In the most recent build, the results are different in the following ways:

`&filter[_id][$in][0]=xxxxxxxxxxxxxxxxxx`
Now works

&filter[_id][$in][0]=xxxxxxxxxxxxxxxxxx&filter[_id][$in][1]=yyyyyyyyyyyyyyyyy
Only shows first entry

`&filter[$or][0][_id]=MyEntryName`
Now works

`&filter[$or][0][_id]=MyEntryName&filter[$or][1][_id]=MyOtherEntryName`
Now works

`&filter[$or][0][name]=MyEntryName`
Works

`&filter[$or][0][name]=MyEntryName&filter[$or][1][name]=MyOtherEntryName`
Works

`&filter[name][$in][0]=MyEntryName`
Now 406s

`&filter[name][$in][0]=MyEntryName&filter[name][$in][1]=MyOtherEntryName`
Now 406s

**Comment by aheinze** [comment]
Hi Gryphon,

could you please check again with the latest code base?

Thanks!

**Comment by gryphonmyers** [comment]
All good now!
