### ISSUE TITLE
[Next] Does the Gallery meta feature from ccb4bba work inside repeater?

### ISSUE THREAD

**Issue by JesperWe** [COCOPi/cockpit#461]
It works fins in single element gallery, but in repeter i have had no success after trying 

```
{
  "fields": [
    {
      "type": "gallery",
      "options": {
        "meta": {
          "color": {
            "type": "color",
            "label": "Text Color Code"
          }
        }
      }
    }
  ]
}
```
and

```
{
  "fields": [
    {
    "type": "gallery",
      "meta": {
        "color": {
          "type": "color",
          "label": "Text Color Code"
        }
      }
    }
  ]
}
```

**Comment by aheinze** [comment]
what is the exact problem here? do the fields don't save the value?

**Comment by JesperWe** [comment]
No, the modal dialog that appears when clicking the meta icon does only contain the Title field, not any of the additional meta fields.

**Comment by aheinze** [comment]
Sorry, but I can't verify that with the latest code base:

![screen](http://g.recordit.co/3rvHeBSy58.gif)

http://recordit.co/3rvHeBSy58

**Comment by JesperWe** [comment]
Ah, ok, it works if you create new galleries. Changing the repeater JSON apparently does not update galleries that are already present.

**Comment by JesperWe** [comment]
I think I will close this. The problem only arises with galleries that were created before the meta feature was implemented, so it has really marginal impact.
