### ISSUE TITLE
"Collection to link not defined in the field settings"

### ISSUE THREAD

**Issue by dujoducom** [COCOPi/cockpit#469]
I'm unsure how to link collections, any ideas?

**Comment by gryphonmyers** [comment]
In the opts for the field, put:
`
{
  "link": "collectionName",
  "multiple": true
}
`
Or if you only want the user to be able to select one entry, leave out the multiple property.

**Comment by dujoducom** [comment]
Great, worked like a charm!

**Comment by dujoducom** [comment]
@gryphonmyers I've added your response to a wiki page I just made: 

https://github.com/COCOPi/cockpit/wiki/Collection-Field-Types

I also found (via trial and error) how to use the "Select" field type, so I've added info there.
