### ISSUE TITLE
Next Branche. Date Field not working.

### ISSUE THREAD

**Issue by scratthunder** [COCOPi/cockpit#476]
I tried to create a Field with a Date entry. When i tried to pick an actual date it doesn't get saved. I get the following in the console:

Uncaught SyntaxError: Unexpected identifier

(anonymous function)	@	riot.bind.js?ver=0.2.7:100
(anonymous function)	@	components.js?ver=0.2.7:1389
dispatch	@	jquery.js?ver=0.2.7:3
q.handle	@	jquery.js?ver=0.2.7:3
trigger	@	jquery.js?ver=0.2.7:4
(anonymous function)	@	jquery.js?ver=0.2.7:4
each	@	jquery.js?ver=0.2.7:2
each	@	jquery.js?ver=0.2.7:2
trigger	@	jquery.js?ver=0.2.7:4
(anonymous function)	@	datepicker.js?v=0.2.7:188
dispatch	@	jquery.js?ver=0.2.7:3
q.handle	@	jquery.js?ver=0.2.7:3

**Comment by aheinze** [comment]
hard to say, need more details which os, browser (+version) etc...

**Comment by scratthunder** [comment]
sry for the lack of details.
Mac 10.12, Chrome 53.0.2785.143

i deleted the collection and redid everything. now its working. I thought I already did that. I consider this issue closed. Sry for bothering.
