### ISSUE TITLE
[Next] REST parameter 'populate' doesn't work for collection links inside repeater fields

### ISSUE THREAD

**Issue by gryphonmyers** [COCOPi/cockpit#477]
1) Create a collection with a repeater field that contains a collection link as one of the field options
2) Add some test data
3) View this collection on the REST API with the populate option set (numerical value of at least 1)
4) Note that it does not populate the nested links - they retain the generic object with 'id' and 'display'

**Comment by aheinze** [comment]
yepp, because it is not implemented (also for "Set" field type).

**Comment by gryphonmyers** [comment]
Ok I can work on implementing this if that would be helpful

**Comment by gryphonmyers** [comment]
#480
