### ISSUE TITLE
Collection view doesn't show the title of the item, instead it just displays ""

### ISSUE THREAD

**Issue by jobsturm** [COCOPi/cockpit#483]

**Comment by aheinze** [comment]
Hi,

could you please give more details? Are you using Next or the legacy version etc.?

Thanks!

**Comment by jobsturm** [comment]
Hey I am using version 13.0 and running it on Wamp.

**Comment by aheinze** [comment]
You need to define in the collection edit which fields should be visible on the entries view ... btw, I would recommend you to start anything new with Cockpit Next

**Comment by jobsturm** [comment]
Thank you a lot! Where can I find Cockpit Next?

**Comment by aheinze** [comment]
https://github.com/COCOPi/cockpit/tree/next

Download:
https://github.com/COCOPi/cockpit/archive/next.zip
