### ISSUE TITLE
Collection view doesn't show the title of the item, instead it just displays "show entry"

### ISSUE THREAD

**Issue by jobsturm** [COCOPi/cockpit#484]
If I am in a collection I created, the overview of the records in that collection doesn't display the title and or other information. Instead it shows me a list of "show item" and the date they were modified.

**Comment by aheinze** [comment]
Do you use the legacy version or Cockpit Next?

**Comment by jobsturm** [comment]
I am using version 13.0 and running it on Wamp 2.5

Also, pardon me for making this issue twice. I do not know how that happened.

**Comment by aheinze** [comment]
Close because of duplicate issue #483
