### ISSUE TITLE
[Next] Delete permissions don't seem to work

### ISSUE THREAD

**Issue by gryphonmyers** [COCOPi/cockpit#492]
I attempted to create a user role that has view and delete perms for a collection, but no edit perms. When attempting to delete an entry (from the triple bar menu on the entry's row in the entries view) it gives no feedback and a 404 error comes up in the log. At first I thought this was because of the lack of edit perms, but it actually does the same thing even if I give full edit rights to a user group, so it actually seems that the delete permission just isn't functioning correctly.

**Comment by aheinze** [comment]
Fixed 👍🏻
