### ISSUE TITLE
Region fields with direct REST calls

### ISSUE THREAD

**Issue by julienr114** [COCOPi/cockpit#493]
Hello, I make a project with cockpit and Vuejs in frontend.
How I can get regions fields without template. I would just a json with region fields like in collections for make my template with vuejs reactivity. Is it possible with a direct REST calls ?

Sorry for my English, I'am a french developer and I don't speak very well.

**Comment by aheinze** [comment]
just added to Cockpit Next. 

```/api/regions/data/{region}```

**Comment by julienr114** [comment]
thanks @aheinze. 
Otherwise I had found another solution. You can write the json directly in the code placeholder instead of the template. But the solution of your commit is much more practical.
