### ISSUE TITLE
Make the CMS SSL compatible

### ISSUE THREAD

**Issue by DaniWinter** [COCOPi/cockpit#495]
I had to change the gravatar url because it was delivered over http:// which defeats the purpose of the SSL certificate.

**Comment by aheinze** [comment]
Do you use Cockpit Next or legacy?

**Comment by DaniWinter** [comment]
I downloaded the stable version from https://getcockpit.com/download

**Comment by DaniWinter** [comment]
Nevermind, didn't realize that the github version and the version on your website were different.
