### ISSUE TITLE
How to use basic things like get a collection?

### ISSUE THREAD

**Issue by DaniWinter** [COCOPi/cockpit#497]
The old documentation doesn't seem to work on Cockpit Next.

**Comment by treechime** [comment]
I found these ways work:

`cockpit("collections")->find('collectionname');`

`cockpit("collections")->findOne('collectionname', ['slug' => $params['slug']]);`

**Comment by DaniWinter** [comment]
Thanks @treechime, it works!

**Comment by DaniWinter** [comment]
Another question, how do I create a slug for a text field?

**Comment by webcliq** [comment]
Surely this and several other "issues" (which are in fact, questions) which are currently open, should be in Google Community Group Cockpit. 

I have already implemented Slugifying a text field, organising a next Reference or a numeric ID but, I do this with Javascript working on an input field with a specific Class as the form loads.

This is to too complicated and not appropriate, to explain as a comment to an Issue.

**Comment by aheinze** [comment]
in cockpit next you need to define ```slug:true``` in the field options for the text field:

```json
{
   "slug": true
}
```
