### ISSUE TITLE
Media with an apostrophe in the filename or pathname don't display

### ISSUE THREAD

**Issue by dcpedit** [COCOPi/cockpit#502]
When browsing media, either the background image is not set, or the apostrophe is not escaped with a backslash in the style url:

`<div class="media-url-preview" style="background-image:url(/media/Learn%20To%20Win%20Or%20You'll%20Take%20Losing%20For%20Granted/assets/LearnToWinOrYoullTakeLosingForGranted9.jpg);background-size:cover;"></div>`

Should be: (note escaped apostrophe in the word **You'll**
`<div class="media-url-preview" style="background-image:url(/media/Learn%20To%20Win%20Or%20You\'ll%20Take%20Losing%20For%20Granted/assets/LearnToWinOrYoullTakeLosingForGranted9.jpg);background-size:cover;"></div>`

**Comment by aheinze** [comment]
Hi,

do you use Cockpit Next or the legacy version?

Greets,
Artur

**Comment by dcpedit** [comment]
This is on the legacy version
