### ISSUE TITLE
SQLlite password

### ISSUE THREAD

**Issue by petrepopescu21** [COCOPi/cockpit#504]
Hi,

I'm looking to back up the data in my sqllite files without exporting everything.
What's the password for the sqllite files?

Regards,
Petre

**Comment by aheinze** [comment]
Hi,

there is no password for the sqlite files, youshould be able to open them with any sqlite manager.

greets,
artur

**Comment by peterbrinck** [comment]
It's probably because the user that runs the Cockpit instance/the Apache server (probably `www-data`) creates the SQLite files when installing Cockpit, and then they're password protected since it's another users files
