### ISSUE TITLE
[Question] URL structure for multilanguage site with Cockpit?

### ISSUE THREAD

**Issue by lswest** [COCOPi/cockpit#518]
I've seen the documentation for Cockpit's localization, which works fine (General -> Settings - >Localize). However, I want to use URLs (or, worst-case, cookies) to save the preferred language from page to page. Such as `/en/bio`. I tried adding in routes to index.php and setting a RewriteRule in .htaccess to deal with en and de in the URL, but haven't had a lot of luck.

Specifically, the issue I'm having is with the .htaccess rule. The standard one is `RewriteRule ^(.*)$ index.php/$1 [QSA,L]`.  I tried to change it so it would accept an option en/de before, like this: `RewriteRule ^(en|de)?/(.*)$ index.php?lang=$1/$2 [QSA,L]`, but that wasn't working. I'm pretty new to writing RewriteRules by hand, and so it's entirely possible I'm missing an obvious mistake, or have misunderstood how the existing rule works.

Before I continue on down this route, is this the preferred/recommended way to do it, or is there something in the Cockpit bootstrap file I'm overlooking? Any examples would be appreciated too!

**Comment by gryphonmyers** [comment]
Personally, I would leave Cockpit as is and access its data over the REST API. Whatever localized routes you create in your app, whether front or back end, accessing the appropriate data on the API should be a simple matter of appending the current locale/language string to the property you access in the JSON object. If you're building a server side app, Artur built a PHP router (that powers Cockpit) https://github.com/aheinze/lime. For front end routing, something like router.js would work.

**Comment by lswest** [comment]
Thanks for the reply. I'm actually trying to do exactly that (if I'm understanding you correctly). I'm using the last example on the Cockpit documentation page for multilanguage sites (`$post['article'];     // default` and `$post['article_cs'];  // localized`). The problem I'm having is with the Routes in Lime, where hard-coding the two languages result in the web server expecting a directory (hence why I was looking at htaccess rules). I'll give it a try later using variables, and see if I have any more luck.

Feel free to close this issue, as based on your reply, I think any further questions I may have should be directed at the lime repository.

**Comment by lswest** [comment]
I'm closing this now. I managed to get it working, using the example from the lime repo page:
```
$app->bind("#/pages/(about|contact)#", function($params) {
    return implode("\n", $params[":captures"]);
});
```

Which I turned into:
```
$app->bind("#/(en|de)?/:slug#", function($params) use($app) {
    $post = collection('Pages')->findOne(["Slug_slug"=>$params['slug']]);
    return $app->render('views/page.php', ['post' => $post]);
});
```

I handle the actual translations in the template, using a basic PHP helper to add the language slug to the field name.

It also turned out that I had somehow forgotten to start my CSS/JS imports with a slash, so it was causing errors from that too, as the paths didn't actually exist. Embarrassing, but hey...
