### ISSUE TITLE
[Next] Is there a way to choose display fields on Collection Link

### ISSUE THREAD

**Issue by manuelkern** [COCOPi/cockpit#539]
Hello,

I would like to display more fields than the entry title. Is there a way to do that on the options of my Collection Link type?

![screen shot 2017-05-18 at 09 14 15](https://cloud.githubusercontent.com/assets/9960641/26190645/dd37b480-3baa-11e7-84ca-77e5f2b329f0.png)

![screen shot 2017-05-18 at 09 16 45](https://cloud.githubusercontent.com/assets/9960641/26190663/e83d6bb8-3baa-11e7-85f9-cc6e58085c93.png)

Thank you very much

**Comment by aheinze** [comment]
Hi, do you mean in the result-set of an api call?

**Comment by manuelkern** [comment]
Hi, yes that is what I meant! Thank you very much for your time and great tool

**Comment by manuelkern** [comment]
sorry in the result-set of an api

**Comment by aheinze** [comment]
may I ask how you query the api?

**Comment by manuelkern** [comment]
I use axios, and make a get url/cockpit/api/collections/get/section?token=

**Comment by aheinze** [comment]
ok, then just add ```populate=1``` to the query parameters

**Comment by manuelkern** [comment]
mhh it still shows only one field of my linked collection

**Comment by manuelkern** [comment]
Maybe I was not clear enough. The response I would like to have should look like this
![screen shot 2017-05-18 at 09 55 16](https://cloud.githubusercontent.com/assets/9960641/26191929/211e2256-3bb0-11e7-90a6-24c1828d7be9.png)
Where "pages" is the linked collection.

**Comment by aheinze** [comment]
right, and the populate parameter tells cockpit to resolve the linked items.

**Comment by aheinze** [comment]
could you share your cockpit installation somewhere?

**Comment by manuelkern** [comment]
sure. Go to manuelkern.com/cockpit

**Comment by aheinze** [comment]
could you please update cockpit to the latest cockpit next version first please

**Comment by manuelkern** [comment]
sorry, I thought I had the latest. I do it

**Comment by manuelkern** [comment]
I took me a bit of time, sorry
manuelkern.com/cockpit-next

**Comment by aheinze** [comment]
http://manuelkern.com/cockpit-next/api/collections/get/section?token=895b6f4c9e7bbed4303f05212f4a6e&populate=1

as you can see, the pages are resolved

**Comment by manuelkern** [comment]
Man thank you soo much

**Comment by aheinze** [comment]
btw the number of the populate parameter tells cockpit how many levels deep it should populate/resolve linked items. so if populate=2 it would also have populate linked items in the linked pages etc.

**Comment by manuelkern** [comment]
Awesome, btw how can I simply update without loosing all my data. Should I copy the storage folder?

**Comment by aheinze** [comment]
yepp, that should do the job
