### ISSUE TITLE
can we have the JSON options back?

### ISSUE THREAD

**Issue by zontarian** [COCOPi/cockpit#541]
Hi,
I wrote a plugin for Cockpit for the release f 2016 that enabled me to use cockpit to generate Hugo pages and run the Hugo bin with a few clicks. It is on github [https://github.com/zontarian/hugocockpit](url)  but sadly it does not work with the new release of Cockpit that uses Angular JS and has many other enhancement/improvements.

So I decided to rewrite it to work again with Cockpit, and since I use AngularJS for other products, it was not terrible, but now I am stuck with a big problem: 
last year Cockpit allowed to add some user defined JSON in the Options field of an entry definition. This allowed my plugin to store Hugo-specific info in the field, and retrieve them. Now this possibility is gone and it hampers badly my workings. 
Is there a way to have it back? Or to enable it?

Thanks
W
This is the old edit of an field in a collection:
![screen shot 2017-05-18 at 13 30 49](https://cloud.githubusercontent.com/assets/2872433/26200435/6ab242da-3bce-11e7-9af9-f0d57edcb9d6.png)

And this is the new one..
![screen shot 2017-05-18 at 13 31 49](https://cloud.githubusercontent.com/assets/2872433/26200437/6e23789e-3bce-11e7-8d3b-49026af21d47.png)

**Comment by aheinze** [comment]
Hi,

I think this is a misunderstanding 

This is the old legacy (not supported) Cockpit version
<img src="https://cloud.githubusercontent.com/assets/2872433/26200437/6e23789e-3bce-11e7-8d3b-49026af21d47.png">

To get the latest Cockpit Next version download: https://github.com/COCOPi/cockpit/archive/next.zip

Greets,
Artur

**Comment by zontarian** [comment]
Ehm.. sorry. I've found all various sites of Cockpit a little bit very confusing, but this was embarassing :)
Thanks
