### ISSUE TITLE
'list' reserved word in PHP 5.5.9

### ISSUE THREAD

**Issue by zontarian** [COCOPi/cockpit#544]
Hi

I've installed cockpit on an Ubuntu with php 5.5.9 and it seems that sometimes, while saving an entry, Cockpit gives an error on `Revisions.php list` definition.

     "PHP message: PHP Parse error:  syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in /data/www/xxxx/demo/cockpit/modules/Cockpit/Helper/Revisions.php on line 18

It appears `list` cannot be a function/method name.

I've changed two files file:

- cockpit/modules/Collections/Controller/Admin.php : 271
- cockpit/modules/Cockpit/Helper/Revisions.php : 18

At the moment I cannot make a pull request.

**Comment by zontarian** [comment]
I've submitted a pull request

**Comment by aheinze** [comment]
merged
